### PR TITLE
Delete permissions resource for auto-purged cluster

### LINKED ISSUE #1227: [ISSUE] Resource `databricks_permissions` doesn't handle error on cluster terminated 30+ days ago
Similar to issue https://github.com/databrickslabs/terraform-provider-databricks/issues/1177 (involving `databricks_cluster` resource). Impact on terraform projects containing unpinned clusters that have been terminated 30+ days ago.

When applying access control policy to the cluster using `resource "databricks_permissions" "cluster_usage"`, it will return the following error message:

> Error: Cannot access cluster <cluster_id> that was terminated or unpinned more than 30 days ago.

### Configuration
```hcl
resource "databricks_permissions" "cluster_usage" {
  cluster_id = databricks_cluster.cluster.cluster_id

  dynamic "access_control" {
    for_each = local.owners
    content {
      user_name        = trimspace(access_control.value)
      permission_level = "CAN_MANAGE"
    }
  }

  access_control {
    group_name       = "Ambassador Data Science (Clusters Managers)"
    permission_level = "CAN_MANAGE"
  }

  access_control {
    group_name       = "Data Engineers"
    permission_level = "CAN_MANAGE"
  }
}
```

### Expected Behavior
As same as `databricks_cluster` resource when handling to clusters terminated 30+ days ago, e.g., the provider should probably treat that specific error message as a "valid action" when the command terraform plan is ran, and address just a warning about cluster state. 

### Actual Behavior
An access cluster error raises and breaks the pipeline.

### Steps to Reproduce

1. Have a terraform project with an unpinned cluster terminated 30+ days ago and thus deleted.
2. `terraform apply`

### Terraform and provider versions

* Terraform: **v1.0.3**
* Databricks provider: **0.5.4**

### Important Factoids
Related to [[ISSUE] Project with cluster terminated 30+ days ago made unusable.](https://github.com/databrickslabs/terraform-provider-databricks/issues/1177) *#1177*

### PR DESCRIPTION
**Pull request by nfx**
Fix #1227

### CODE REVIEW

File: permissions/resource_permissions.go [hunk 1]
```diff
@@ -203,6 +203,16 @@ func (a PermissionsAPI) Delete(objectID string) error {
 // Read gets all relevant permissions for the object, including inherited ones
 func (a PermissionsAPI) Read(objectID string) (objectACL ObjectACL, err error) {
 	err = a.client.Get(a.context, urlPathForObjectID(objectID), nil, &objectACL)
+	apiErr, ok := err.(common.APIError)
+	// https://github.com/databrickslabs/terraform-provider-databricks/issues/1227
+	// platform propagates INVALID_STATE error for auto-purged clusters in 
+	// the permissions api. this adds "a logical fix" also here, not to introduce
+	// cross-package dependency on "clusters".
+	if ok && strings.Contains(apiErr.Message, "Cannot access cluster") {
```
Comment (pietern) [inline permissions/resource_permissions.go:211]: Also test for `apiErr.StatusCode`? I expect it to be stable for this error message.

Comment (nfx) [reply permissions/resource_permissions.go:211]: fixed in #1253
