### PR TITLE
Implicitly force import manually added group

### LINKED ISSUE #1066: force ignore existing groups - like for users
Federation using SCIM can pre create  groups that will cause TF to fail if they exist.
The provider should have the `force` option for **groups** to ignore `cannot create group: ... already exists` errors and implicitly import the specific group into Terraform state.

Same problem, accepted and solved via #1048 for **users**, should be solved same way for **groups** as well.

Using `data "databricks_group"` data provider is not possible if the existence of the group is not known upfront. The data provider should also gracefully fail.

### Expected Behavior

allowing to ignore that case and implicitly import the specific group into Terraform state.

### Actual Behavior
erroring out

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions

v0.4.2

### PR DESCRIPTION
**Pull request by nkvuong**
Add `force` parameter to `databricks_group`, so that SCIM sync corner cases might be simplified

image

Closes #1066

### CODE REVIEW

File: scim/resource_group.go [hunk 1]
```diff
@@ -61,3 +68,23 @@ func ResourceGroup() *schema.Resource {
 		Schema: groupSchema,
 	}.ToResource()
 }
+
+func createForceOverridesManuallyAddedGroup(err error, d *schema.ResourceData, groupsAPI GroupsAPI, g Group) error {
+	forceCreate := d.Get("force").(bool)
+	if !forceCreate {
+		return err
+	}
+	// corner-case for overriding manually provisioned users
```
Comment (nfx) [inline scim/resource_group.go:77]: not _users_ ;)

File: scim/resource_group.go [hunk 2]
```diff
@@ -61,3 +68,23 @@ func ResourceGroup() *schema.Resource {
...
+	groupName := g.DisplayName
+	force := fmt.Sprintf("Group with name %s already exists.", groupName)
+	if err.Error() != force {
+		return err
+	}
+	groupList, err := groupsAPI.Filter(fmt.Sprintf("displayName eq '%s'", groupName))
```
Comment (nfx) [inline scim/resource_group.go:83]: use `ReadByDisplayName` method instead: https://github.com/databrickslabs/terraform-provider-databricks/blob/2d138fb6b7822f67a13ccbfee7c1c2ad32f54b36/scim/groups.go#L52-L63

**Review by nfx — CHANGES_REQUESTED** [review]
+ change CHANGELOG.md and docs/resources/group.md - make sure to add "experimental" label to it, as in user resource.
+ cover missing line with test (probably test will be simpler if you use ReadByDisplayName)

**Review by nfx — APPROVED** [review]
