### PR TITLE
Fix #323 - add DiffSuppressFunc for legacy conf

### LINKED ISSUE #323: [ISSUE] databricks_job resources are always updated even when no changes
### Terraform Version
```
Terraform v0.13.2
+ provider registry.terraform.io/databrickslabs/databricks v0.2.5
```

### Affected Resource(s)
- databricks_job

### Terraform Configuration Files
```hcl
resource "databricks_job" "test" {

  name = "Test"
  timeout_seconds = 1800
  max_retries = 1
  max_concurrent_runs = 1

  new_cluster {
    num_workers = 1
    spark_version = "7.2.x-scala2.12"
    node_type_id = "Standard_DS3_v2"
  }

  notebook_task {
    notebook_path = "/jobs/test"
    base_parameters = {
      param1 = "2"
      param2 = "false"
    }
  }

  email_notifications {
    on_failure = ["redacted1@email.com", "redacted2@email.com", "redacted3@email.com"]
  }

  schedule {
    timezone_id = "America/New_York"
    quartz_cron_expression = "0 0 * ? * * *" # hourly
  }
}

```

### Expected Behavior
After the job is created, when there are no changes to the configuration terraform should not try to change it.

### Actual Behavior
After initial creation, on each run of `terraform plan` / `terraform apply` it says there are changes for the job. Example plan below:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # databricks_job.salesforce will be updated in-place
  ~ resource "databricks_job" "test" {
        id                        = "8761"
        library_cran              = []
        library_egg               = []
        library_jar               = []
        library_maven             = []
        library_pypi              = []
        library_whl               = []
        max_concurrent_runs       = 1
        max_retries               = 1
        min_retry_interval_millis = 0
        name                      = "Test"
        retry_on_timeout          = false
        timeout_seconds           = 1800

        email_notifications {
            no_alert_for_skipped_runs = false
            on_failure                = [
                "redacted1@email.com",
                "redacted2@email.com",
                "redacted3@email.com",
            ]
            on_start                  = []
            on_success                = []
        }

      ~ new_cluster {
            autotermination_minutes      = 0
            custom_tags                  = {}
            enable_elastic_disk          = true
            enable_local_disk_encryption = false
            node_type_id                 = "Standard_DS3_v2"
            num_workers                  = 1
          ~ spark_conf                   = {
              - "spark.databricks.delta.preview.enabled" = "true" -> null
            }
            spark_env_vars               = {}
            spark_version                = "7.2.x-scala2.12"
            ssh_public_keys              = []
        }

        notebook_task {
            base_parameters = {
                "param1" = "2"
                "param2"   = "false"
            }
            notebook_path   = "/jobs/test"
        }

      ~ schedule {
          - pause_status           = "UNPAUSED" -> null
            quartz_cron_expression = "0 0 * ? * * *"
            timezone_id            = "America/New_York"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

In the `new_cluster` block it is trying to set `spark_conf` to the default (which I did not explicitly configure), and in the `schedule` block it is trying to set the `pause_status` to the default.

### Steps to Reproduce
Create the job by running `terraform apply`, then immediately run `terraform apply` again.

### Important Factoids
Running in Azure Databricks

As a workaround I can set `spark_conf` and `pause_status` to their default values and then no changes are detected with `plan` / `apply`.

### PR DESCRIPTION
**Pull request by nfx**

### CODE REVIEW

File: compute/resource_job.go [hunk 1]
```diff
@@ -92,6 +93,17 @@ var jobSchema = internal.StructToSchema(JobSettings{},
...
 			"[databricks_cluster](cluster.md) resource."
+		if v, err := internal.SchemaPath(s, "new_cluster", "spark_conf"); err == nil {
+			v.DiffSuppressFunc = func(k, old, new string, d *schema.ResourceData) bool {
+				isPossiblyLegacyConfig := "new_cluster.0.spark_conf.%" == k && "1" == old && "0" == new
+				isLegacyConfig := "new_cluster.0.spark_conf.spark.databricks.delta.preview.enabled" == k
+				if isPossiblyLegacyConfig || isLegacyConfig {
+					log.Printf("[DEBUG] Suppressing diff for k=%#v old=%#v new=%#v", k, old, new)
+					return true
+				}
+				return false
```
Comment (alexott) [inline compute/resource_job.go:104]: does it make sense to move it into shared function, because the difference is only that this function is different only in prefix `spark_conf.` vs `new_cluster.0.spark_conf.`

**Review by alexott — APPROVED** [review]
looks good, with small comment about code duplication

File: compute/resource_job.go (hunk 1 above)
Comment (stikkireddy) [reply compute/resource_job.go:104]: hmm are we even sure if this is relevant to jobs? AFAIK when i create a job without spark configs that job does not have spark configs configured by default it only happens in the clusters api.

Comment (stikkireddy) [reply compute/resource_job.go:104]: I verified with the following create payload:

```json
{
   "name":"Nightly model training",
   "new_cluster":{
      "spark_version":"5.3.x-scala2.11",
      "node_type_id":"r3.xlarge",
      "aws_attributes":{
         "availability":"ON_DEMAND"
      },
      "num_workers":10
   },
   "libraries":[
      {
         "jar":"dbfs:/my-jar.jar"
      },
      {
         "maven":{
            "coordinates":"org.jsoup:jsoup:1.7.2"
         }
      }
   ],
   "email_notifications":{
      "on_start":[
         
      ],
      "on_success":[
         
      ],
      "on_failure":[
         
      ]
   },
   "timeout_seconds":3600,
   "max_retries":1,
   "schedule":{
      "quartz_cron_expression":"0 15 22 ? * *",
      "timezone_id":"America/Los_Angeles"
   },
   "spark_jar_task":{
      "main_class_name":"com.databricks.ComputeModels"
   }
}
```

The response from the GET:

```json
{
    "job_id": 4393,
    "settings": {
        "name": "Nightly model training",
        "new_cluster": {
            "spark_version": "5.3.x-scala2.11",
            "aws_attributes": {
                "zone_id": "us-west-2b",
                "availability": "ON_DEMAND"
            },
            "node_type_id": "r3.xlarge",
            "enable_elastic_disk": false,
            "num_workers": 10
        },
        "libraries": [
            {
                "jar": "dbfs:/my-jar.jar"
            },
            {
                "maven": {
                    "coordinates": "org.jsoup:jsoup:1.7.2"
                }
            }
        ],
        "email_notifications": {},
        "timeout_seconds": 3600,
        "max_retries": 1,
        "schedule": {
            "quartz_cron_expression": "0 15 22 ? * *",
            "timezone_id": "America/Los_Angeles",
            "pause_status": "UNPAUSED"
        },
        "spark_jar_task": {
            "jar_uri": "",
            "main_class_name": "com.databricks.ComputeModels",
            "run_as_repl": true
        },
        "max_concurrent_runs": 1
    },
    "created_time": 1600863327560,
    "creator_user_name": "sri.tikkireddy@databricks.com"
}
```

As you can see there is no conf auto added. Just the api for clusters being a bit bizarre 😄

Comment (stikkireddy) [reply compute/resource_job.go:104]: hmm i guess they are seeing different behavior in here: https://github.com/databrickslabs/terraform-provider-databricks/issues/323. Which is inconsistent to what i am seeing so then i guess we may need this but it is bizarre. 

And not repeatable.

**Review by stikkireddy — COMMENTED** [review]
LGTM but the behavior of the jobs apis are not consistent across azure and aws. LGTM for now this should resolve that but probably should see if we remove these returns from api calls.

File: compute/resource_job.go (hunk 1 above)
Comment (nfx) [reply compute/resource_job.go:104]: So because of azure, we have to suppress diffs :)
