### PR TITLE
Fix `job_cluster`.`num_workers` in `databricks_job`

### LINKED ISSUE #1262: [ISSUE] Shared Job Cluster block incompatible with autoscale
Hi there,

I am attempting to use shared job_cluster on a multi-tasks job to minimize costs. However, it appears that the `job_cluster` block doesn't allow the use of the `autoscale` argument and requires `num_worker` instead.

### Configuration
```hcl
resource "databricks_job" "myjob_silvergold_weekly" {
  name = "myjob_silvergold_weekly_${var.common.environment}"
  max_retries = 3
  max_concurrent_runs = 1

  job_cluster {
    job_cluster_key = "xs1"
    new_cluster {
      spark_version           = "9.1.x-scala2.12"
      node_type_id            = "i3.2xlarge"
      driver_node_type_id     = "i3.2xlarge"
      enable_local_disk_encryption = true

      autoscale {
        min_workers = 1
        max_workers = 2
      }
      cluster_log_conf {
        dbfs {
          destination = "dbfs:/cluster-logs"
        }
      }  
      
      aws_attributes {
        instance_profile_arn    = local.instance_profile_arn
        availability            = "SPOT_WITH_FALLBACK"
        first_on_demand         = 1
        spot_bid_price_percent  = 100
        zone_id                 = "eu-west-1"
      } 
    }
  }
	
  task {
    task_key = "1"
    job_cluster_key = "xs1"
    notebook_task {
      notebook_path = databricks_notebook.my_notebook.path
      base_parameters =merge(local.base_params, local.my_notebook_params, {})
    }   
    library {
        jar = databricks_dbfs_file.fuelcompass_scala_utils.dbfs_path
    }
  
    library {
      whl = databricks_dbfs_file.fuelcompass_library.dbfs_path
    }
  
    library {
      whl = databricks_dbfs_file.encryption_library.dbfs_path
    }
  }
}
```

### Expected Behavior
A shared job cluster with specificed autoscaling is created.

### Actual Behavior
`terraform validate` fails.

### Steps to Reproduce
1. `terraform validate`

### Terraform and provider versions

Terraform v1.0.1
Databricks provider V0.5.5

### Debug Output

```hcl
╷
│ Error: Missing required argument
│ 
│   on databricks-weekly-job.tf line 7, in resource "databricks_job" "[MASKED]_silvergold_weekly":
│   7:     new_cluster {
│ 
│ The argument "num_workers" is required, but no definition was found.
╵
╷
```
Debug logs seem to contain no further relevant information (the full logs are 1500 lines long, but research on words like "job", cluster", "worker" and "autoscale" brings no result)

### Important Factoids

I checked through the provider code and couldn't see anything that would look out of place. JobCluster calls the same NewCluster API than JobTaskSettings. However, there's a [jobSettingsSchema function](https://github.com/databrickslabs/terraform-provider-databricks/blob/fe4a830bf3394b9d1be7b8ba3fe90efc1387f122/jobs/resource_job.go#L419) that seems to do something with `num_worker` that may not be properly applied when it's in the `job_cluster` block? I couldn't find anything directly related to autoscale however.

Kind regards

### PR DESCRIPTION
**Pull request by nfx**
Apply standard schema modification rules to `num_workers` field in shared job clusters.

Fix #1262

### CODE REVIEW

File: jobs/resource_job.go [hunk 1]
```diff
@@ -450,6 +450,7 @@ var jobSchema = common.StructToSchema(JobSettings{},
 	func(s map[string]*schema.Schema) map[string]*schema.Schema {
 		jobSettingsSchema(&s, "")
 		jobSettingsSchema(&s["task"].Elem.(*schema.Resource).Schema, "task.0.")
+		jobSettingsSchema(&s["job_cluster"].Elem.(*schema.Resource).Schema, "job_cluster.0.")
```
Comment (pietern) [inline jobs/resource_job.go:453]: What about jobs with multiple tasks?

I assume `.0.` is a proxy for `.N.`?
