### PR TITLE
Explicitly set charset for SCIM requests

### LINKED ISSUE #1034: Creating databricks groups with æøå does not work
**databricks provider:** 0.4.4
**Issue:** creating groups containing special characters (for example æøå ) gets wrong/different encoding in Databricks Workspace.

Example:
resource "databricks_group" "æøå-test" {
  display_name          = "æøå"
}

causes issue:
```
{
    "@level": "warn",
    "@message": "Provider \"provider[\\\"registry.terraform.io/databrickslabs/databricks\\\"]\" produced an unexpected new value for databricks_group.æøå-test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .display_name: was cty.StringVal(\"æøå\"), but now cty.StringVal(\"Ã¦Ã¸Ã¥\")",
    "@timestamp": "2022-01-13T12:30:04.589586Z"
}
```

Making the name not match between configuration and Databricks Workspace deployed groups and configuration providing changes on every plan:
```
  # databricks_group.æøå-test must be replaced
-/+ resource "databricks_group" "æøå-test" {
      ~ display_name               = "Ã¦Ã¸Ã¥" -> "æøå" # forces replacement
      ~ id                         = "944677071884272" -> (known after apply)
        # (5 unchanged attributes hidden)
    }
```

### PR DESCRIPTION
**Pull request by alexott**
This fixes #1034

Also, added printing of response headers when debugging is enabled

### CODE REVIEW

File: common/http.go [hunk 1]
```diff
@@ -486,7 +487,16 @@ func (c *DatabricksClient) genericQuery(ctx context.Context, method, requestURL
...
-	log.Printf("[DEBUG] %s %v <- %s %s", resp.Status, c.redactedDump(body), method, request.URL.Path)
+	headers = ""
+	if c.DebugHeaders {
+		for k, v := range resp.Header {
+			headers += fmt.Sprintf("\n * %s: %s", k, onlyNBytes(strings.Join(v, ""), c.DebugTruncateBytes))
+		}
+		if len(headers) > 0 {
+			headers += "\n"
+		}
+	}
```
Comment (nfx) [inline common/http.go:498]: can you make it into a function, as lines 455-464 are exactly the same.

**Review by nfx — CHANGES_REQUESTED** [review]
please fix code duplication

File: common/http.go (hunk 1 above)
Comment (alexott) [reply common/http.go:498]: ok

**Review by nfx — APPROVED** [review]
