### PR TITLE
Use correct verb for permissions on SQL Endpoint

### LINKED ISSUE #1163: SQL Endpoint Permissions - Unable to remove permissions
`databricks_permissions` resource doesn't remove permissions when applied to SQL Endpoints

# Configuration
The following configuration comments out GROUP_TO_REMOVE. On Terarform apply, the Group should be removed from SQL endpoint permissions
```
resource "databricks_permissions" "sql_endpoint_test" {
  sql_endpoint_id = databricks_sql_endpoint.test.id

  access_control {
    group_name       = "GROUP_TO_KEEP"
    permission_level = "CAN_USE"
  }
  
  # REMOVE THIS GROUP
  #access_control {
  #  group_name       = "GROUP_TO_REMOVE"
  #  permission_level = "CAN_USE"
  #}

}
```

Terarform apply shows changes successfully applied:
```
Terraform will perform the following actions:

  # databricks_permissions.sql_endpoint_test will be updated in-place
  ~ resource "databricks_permissions" "sql_endpoint_test" {
        id              = "/sql/endpoints/f9e5be351fb914fb"
        # (2 unchanged attributes hidden)

      - access_control {
          - group_name       = "GROUP_TO_REMOVE" -> null
          - permission_level = "CAN_USE" -> null
        }
      + access_control {
          + group_name       = "GROUP_TO_KEEP"
          + permission_level = "CAN_USE"
        }
      - access_control {
          - group_name       = "GROUP_TO_KEEP" -> null
          - permission_level = "CAN_USE" -> null
        }
    }
	
Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

# Expected Behaviour
After a Terraform apply, GROUP_TO_REMOVE is removed from permissions on Databricks SQL Endpoint

# Actual Behaviour
GROUP_TO_REMOVE doesn't get removed on the Databricks SQL Endpoint. Performing a subsequent plan/apply shows same changes need to be made
```
Terraform will perform the following actions:

  # databricks_permissions.sql_endpoint_test will be updated in-place
  ~ resource "databricks_permissions" "sql_endpoint_test" {
        id              = "/sql/endpoints/f9e5be351fb914fb"
        # (2 unchanged attributes hidden)

      - access_control {
          - group_name       = "GROUP_TO_REMOVE" -> null
          - permission_level = "CAN_USE" -> null
        }
      + access_control {
          + group_name       = "GROUP_TO_KEEP"
          + permission_level = "CAN_USE"
        }
      - access_control {
          - group_name       = "GROUP_TO_KEEP" -> null
          - permission_level = "CAN_USE" -> null
        }
    }
	
Plan: 0 to add, 1 to change, 0 to destroy.
```

# Steps to reproduce
Apply a databricks_permissions resource on an sql endpoint with an initial set of group permissions. Remove a group permission and run a Terraform apply. The group is not removed.

# Terraform and provider versions

Terarform Version `1.0.11`
Databricks Provider `0.5.2`

# Important Factoids

Looking at the DEBUG logs, it seems a PATCH API call is done. Reading the Databricks API docs, shouldn't that be a PUT API call, so that user permisions are overwritten? 

```
2022-03-07T13:22:40.401-0500 [DEBUG] provider.terraform-provider-databricks_v0.5.2: PATCH /api/2.0/permissions/sql/endpoints/f9e5be351fb914fb {
  "access_control_list": [
    {
      "group_name": "GROUP_TO_KEEP",
      "permission_level": "CAN_USE"
    },
    {
      "permission_level": "CAN_MANAGE",
      "user_name": "<redacted>"
    }
  ]
}: timestamp=2022-03-07T13:22:40.401-0500
2022-03-07T13:22:40.801-0500 [DEBUG] provider.terraform-provider-databricks_v0.5.2: 200 OK  {
  "access_control_list": [
    {
      "all_permissions": [
        {
          "inherited": false,
          "permission_level": "CAN_MANAGE"
        }
      ],
      "service_principal_name": "<redacted>"
    },
    {
      "all_permissions": [
        {
          "inherited": false,
          "permission_level": "CAN_USE"
        }
      ],
      "group_name": "GROUP_TO_REMOVE"
    },
    {
      "all_permissions": [
        {
          "inherited": false,
          "permission_level": "CAN_USE"
        }
      ],
      "group_name": "GROUP_TO_KEEP"
    },
      {
      "all_permissions": [
      ... (295 more bytes) <- PATCH /api/2.0/permissions/sql/endpoints/f9e5be351fb914fb: timestamp=2022-03-07T13:22:40.801-0500
```

PATCH /permissions/sql/endpoints/{endpoint_id}
https://docs.databricks.com/dev-tools/api/latest/permissions.html#operation/set-sqlendpoint-permissions
Grant SQL endpoint permissions for one or more users, groups, or service principals.
This request only grants (adds) permissions. To revoke, use the replace all SQL endpoint permissions operation.

PUT /permissions/sql/endpoints/{endpoint_id}
https://docs.databricks.com/dev-tools/api/latest/permissions.html#operation/update-all-sqlendpoint-permissions
Update all permissions for a specific SQL endpoint, specifying all users, groups or service principal.
WARNING: This request overwrites all existing direct (non-inherited) permissions on the SQL endpoint and replaces it with the new permissions specified in the request body.

### PR DESCRIPTION
**Pull request by nfx**
Use correct HTTP verb for `databricks_permissions` on `databricks_sql_endpoint`. Authorized user, assumingly part of `admins` group, is no longer sending `CAN_MANAGE` permission in the HTTP PUT request.

Fixes #1163

### CODE REVIEW

File: permissions/resource_permissions.go [hunk 1]
```diff
@@ -131,15 +135,9 @@ func (a PermissionsAPI) put(objectID string, objectACL AccessControlChangeList)
 			UserName:        me.UserName,
 			PermissionLevel: "CAN_MANAGE",
```
Comment (pietern) [inline permissions/resource_permissions.go:136]: Is this implied permission also gone?

File: CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,7 @@
 
 * Failures in [exporter](https://asciinema.org/a/Rv8ZFJQpfrfp6ggWddjtyXaOy) resource listing no longer halt the entire command run ([#1166](https://github.com/databrickslabs/terraform-provider-databricks/issues/1166)).
 * Removed client-side validation in `databricks_service_principal` for `application_id`, that may not always be available in the planning stage ([#1165](https://github.com/databrickslabs/terraform-provider-databricks/issues/1165)).
+* Use correct HTTP verb for `databricks_permissions` on `databricks_sql_endpoint`. Authorized user, assumingly part of `admins` group, is no longer sending `CAN_MANAGE` permission in the HTTP PUT request ([#1163](https://github.com/databrickslabs/terraform-provider-databricks/issues/1163)).
```
[the remark this answers is not in the document]
Comment (nfx) [reply CHANGELOG.md:7]: TF just replaces permissions on create/update/delete to follow IaC semantics, which means `PUT` everywhere.

File: permissions/resource_permissions.go (hunk 1 above)
Comment (nfx) [reply permissions/resource_permissions.go:136]: yes, all admins can manage everything, except passwords and tokens, though they can manage permissions for that as well, because they're admins.

File: CHANGELOG.md (hunk 2 above)
[the remark this answers is not in the document]
Comment (pietern) [reply CHANGELOG.md:7]: I see now, it refers to the second bit of the PR.

**Review by pietern — APPROVED** [review]

File: permissions/resource_permissions.go (hunk 1 above)
Comment (nfx) [reply permissions/resource_permissions.go:136]: yep, so endpoints can only be admin-created, so admins cannot loose control by design
