### PR TITLE
[bugfix] "Secret scope ACL is MANAGE for all users by default"

### LINKED ISSUE #322: [ISSUE] Secret scope ACL is set to MANAGE for all users by default and no way to override
### Terraform Version
```
Terraform v0.13.2
+ provider registry.terraform.io/databrickslabs/databricks v0.2.4
```

### Affected Resource(s)
- `databricks_secret_scope`

### Terraform Configuration Files
```hcl
resource "databricks_secret_scope" "test" {
  name = "test"
}
```

### Expected Behavior
A secret scope is created with only the user whose databricks authentication is being used having MANAGE access

### Actual Behavior
All users are given MANAGE access to the secret scope

### Steps to Reproduce
1. `terraform apply`

The underlying issue appears to be that the Databricks API is somewhat limited and requires that `initial_manage_principal` be omitted OR be set to `users`. Surprisingly it does not allow a caller to specify a specific desired manage principal, even if you set the principal to match the calling user.

In the provider code I see that there's a default value of `Users` set for this field: https://github.com/databrickslabs/terraform-provider-databricks/blob/master/access/resource_secret_scope.go#L83

There should be no default for this field if it's not present, because the API sets the value to the current user only if the parameter is not present in the API call. Any other value is rejected by the API with a 400 error code.

### PR DESCRIPTION
**Pull request by alexott**
If the scope is defined with `initial_manage_principal = ""`, then the corresponding field is omitted from the request body, and as result, `users` group won't get the `MANAGE` permission for created scope as [described in Secrets API docs](https://docs.databricks.com/dev-tools/api/latest/secrets.html#create-secret-scope).

This fixes #322

### CODE REVIEW

**Comment by nfx** [comment]
not to forget adding this comment later:

1. entry within `changelog.md`
2. updated documentation for markdown file
3. integration and/or acceptance test

**Comment by alexott** [comment]
@nfx updated with a new version

File: access/resource_secret_scope.go [hunk 1]
```diff
@@ -80,7 +84,6 @@ func ResourceSecretScope() *schema.Resource {
 				Optional: true,
 				ForceNew: true,
 				// or creator...
```
Comment (nfx) [inline access/resource_secret_scope.go:86]: please also remove this comment, that's not pointing to any line :)

File: access/acceptance/secret_acl_test.go [hunk 2]
```diff
@@ -132,3 +147,18 @@ func testSecretACLResource(scopeName, principal, permission string) string {
...
 }
+
+// testAccTokenResource returns an configuration for an Example Widget with the provided name
+func testSecretACLResourceWithDefaultPrincipal(scopeName, default_principal, principal, permission string) string {
+	return fmt.Sprintf(`
+		resource "databricks_secret_scope" "my_scope" {
+			name = "%s"
+            initial_manage_principal = "%s"
+		}
+		resource "databricks_secret_acl" "my_secret_acl" {
```
Comment (nfx) [inline access/acceptance/secret_acl_test.go:158]: so to test this, you should only create `databricks_secret_scope` and check what ACLs are returned through `NewSecretAclsAPI` in a custom resource check. In this integration test you're changing existing resource, which is not really testing the case of the bug, so i'd ask to create new `TestAcc...` for it.

File: access/resource_secret_scope.go [hunk 3]
```diff
@@ -21,10 +21,14 @@ type SecretScopesAPI struct {
 
 // Create creates a new secret scope
 func (a SecretScopesAPI) Create(scope string, initialManagePrincipal string) error {
-	return a.C.Post("/secrets/scopes/create", map[string]string{
-		"scope":                    scope,
-		"initial_manage_principal": initialManagePrincipal,
-	}, nil)
+	paramsMap := map[string]string{
+		"scope": scope,
```
Comment (nfx) [inline access/resource_secret_scope.go:25]: if `initialManagePrincipal`, isn't it omitting it on marshaller side?..

File: docs/resources/secret_scope.md [hunk 4]
```diff
@@ -23,7 +23,7 @@ resource "databricks_secret_scope" "my-scope" {
 The following arguments are supported:
 
 * `name` - (Required) Scope name requested by the user. Scope names are unique. This field is required.
-* `initial_manage_principal` - (Optional) The principal that is initially granted MANAGE permission to the created scope.
+* `initial_manage_principal` - (Optional) The principal that is initially granted `MANAGE` permission to the created scope.  If it's omitted, then the initial ACL with `MANAGE` permission applied to the scope is assigned to the API request issuer's user identity (see [documentation](https://docs.databricks.com/dev-tools/api/latest/secrets.html#create-secret-scope)).
```
Comment (nfx) [inline docs/resources/secret_scope.md:26]: you can get `API request issuer's user identity` within the test by calling `Me()` function from UsersAPI

**Review by nfx — CHANGES_REQUESTED** [review]
Refactor test step into it's own integration test, so that we can test the creation of a secret scope.

File: access/resource_secret_scope.go (hunk 3 above)
Comment (alexott) [reply access/resource_secret_scope.go:25]: it's omitted only when used in struct fields, annotated with `omitempty`

Comment (nfx) [reply access/resource_secret_scope.go:25]: Thanks for confirming. For GET requests, where map turns into a query string - it’s omitted, just in case.

**Comment by alexott** [comment]
@nfx all comments were addressed... The code coverage change - maybe because of new functions where we don't have test cases fir `if err != nil` cases.

File: access/acceptance/secret_acl_test.go (hunk 2 above)
Comment (nfx) [reply access/acceptance/secret_acl_test.go:190]: to rephrase previous comment - can you remove `databricks_secret_acl.my_secret_acl`, because this test should verify if there's no ACL for `users` when `initial_manage_principal` is not set.

File: access/acceptance/secret_acl_test.go [hunk 5]
```diff
@@ -69,6 +70,44 @@ func TestAccSecretAclResource(t *testing.T) {
...
 
+func TestAccSecretAclResourceDefaultPrincipal(t *testing.T) {
+	// TODO: refactor for common instance pool & AZ CLI
+	if _, ok := os.LookupEnv("CLOUD_ENV"); !ok {
+		t.Skip("Acceptance tests skipped unless env 'CLOUD_ENV' is set")
+	}
+	//var secretScope Secre
+	var secretACL ACLItem
+	scope := fmt.Sprintf("tf-scope-%s", acctest.RandStringFromCharSet(10, acctest.CharSetAlphaNum))
+	initialPrincipal := "users"
```
Comment (nfx) [inline access/acceptance/secret_acl_test.go:81]: we need two different automated tests for this PR:

1) `initial_manage_principal` is not set and verify, that only admins can manage this scope.
2) `initial_manage_principal` set to group created specifically for this test and verify that only that group and admins can manage this scope.

**Review by nfx — CHANGES_REQUESTED** [review]
we need two different automated tests for this PR:

* initial_manage_principal is not set and verify, that only admins can manage this scope.
* initial_manage_principal set to group created specifically for this test and verify that only that group and admins can manage this scope.

File: access/acceptance/secret_acl_test.go (hunk 5 above)
Comment (alexott) [reply access/acceptance/secret_acl_test.go:81]: we can't use arbitrary group for `initial_principal` as per [documentation](https://docs.databricks.com/dev-tools/api/latest/secrets.html#create-secret-scope): 

> The only supported principal for this option is the group users, which contains all users in the workspace.

and if I create any other group, and use it as initial principal, then Secrets API returns error saying that I can't use that group as initial principal

Comment (nfx) [reply access/acceptance/secret_acl_test.go:81]: > and if I create any other group, and use it as initial principal, then Secrets API returns error saying that I can't use that group as initial principal

that one is strange. what about user?

Comment (alexott) [reply access/acceptance/secret_acl_test.go]: same - you can't explicitly set user as `initial_principal` as well, but this happens implicitly when no `initial_principal` is provided - I've added corresponding test that checks that user has MANAGE permission for scope if `initial_principal` is not provided.

But I think that we need to talk with developers to understand that design decision, I also wondering why this happens...

File: access/acceptance/secret_acl_test.go [hunk 6]
```diff
@@ -26,6 +27,9 @@ func TestAccSecretAclResource(t *testing.T) {
 	scope := fmt.Sprintf("tf-scope-%s", acctest.RandStringFromCharSet(10, acctest.CharSetAlphaNum))
 	principal := "users"
 	permission := "READ"
+	client := common.CommonEnvironmentClient()
+	me, _ := identity.NewUsersAPI(client).Me()
```
Comment (nfx) [inline access/acceptance/secret_acl_test.go:31]: this is called "ignoring the error". we must handle errors everywhere, assert.NoError(t,err) in tests as well.

**Review by nfx — APPROVED** [review]

File: access/acceptance/secret_acl_test.go (hunk 6 above)
Comment (alexott) [reply access/acceptance/secret_acl_test.go:31]: just pushed the modified version, but it was already merged - will fix in the next iteration, when will do #235
