### PR TITLE
Remove failed libraries on running clusters

### LINKED ISSUE #599: Remove managed library that failed to install on refresh
Remove managed library that failed to install on refresh

### PR DESCRIPTION
**Pull request by nfx**
Whenever a library fails to get installed on a running cluster, we automatically remove it, so that the clean state of managed libraries is properly maintained. Without this fix users had to manually go to Clusters UI and remove library from a cluster, where it failed to install. Libraries add up to CREATE and UPDATE timeouts of `databricks_cluster` resource.

Fixes #599

### CODE REVIEW

File: libraries/libraries_api.go [hunk 1]
```diff
@@ -243,10 +281,10 @@ func (cll *ClusterLibraryList) String() string {
 
 // LibraryStatus is the status on a given cluster when using the libraries status api
 type LibraryStatus struct {
-	Library                         *Library `json:"library,omitempty"`
-	Status                          string   `json:"status,omitempty"`
-	IsLibraryInstalledOnAllClusters bool     `json:"is_library_for_all_clusters,omitempty"`
-	Messages                        []string `json:"messages,omitempty"`
+	Library  *Library `json:"library,omitempty"`
+	Status   string   `json:"status,omitempty"`
+	IsGlobal bool     `json:"is_library_for_all_clusters,omitempty"`
```
Comment (alexott) [inline libraries/libraries_api.go:286]: should we start deprecation of this flag? Because per [documentation](https://docs.databricks.com/libraries/cluster-libraries.html#library):
>  This option does not install the library on clusters running Databricks Runtime 7.0 and above.

**Review by alexott — APPROVED** [review]
lgtm

File: libraries/libraries_api.go (hunk 1 above)
Comment (nfx) [reply libraries/libraries_api.go:286]: It's not changeable by users anymore 🤷🏻‍♂️ but there still might be some workspaces with dbr7.0, that have this
