### PR TITLE
ISSUE-1120 Cluster Exporter uses Policy ID as value rather than reference

### LINKED ISSUE #1120: [ISSUE] Cluster Exporter uses Policy ID as value rather than reference
When exporting a cluster that has a policy attached, the Policy Id comes in as a value rather than a reference.

### Configuration
```bash
./terraform-provider-databricks exporter     \
-services=groups,secrets,access,compute,users,jobs,storage     \
-listing=jobs,compute    \
 -last-active-days=90    \
 -module=data_platform    \
 -debug
```

### Expected Behavior
What should have happened?
```terraform
resource "databricks_cluster" "dlyle_test_photon_0119_213156_fax211" {
  spark_version = "10.2.x-photon-scala2.12"
  policy_id     = databricks_cluster_policy.cost_center_10011.id
```
### Actual Behavior
What actually happened?
```terraform
resource "databricks_cluster" "dlyle_test_photon_0119_213156_fax211" {
  spark_version = "10.2.x-photon-scala2.12"
  policy_id     = "1961AD0D7C000012"
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a cluster with an attached cluster policy.
2. Run the exporter as shown above
3. Notice that the Policy ID is a value rather than a resource reference.

### Terraform and provider versions

```bash
terraform version
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.4.9
```

### PR DESCRIPTION
**Pull request by david-lyle**
Add to path values in importables.go

Fixes #1120

### CODE REVIEW

File: exporter/importables.go [hunk 1]
```diff
@@ -207,6 +207,7 @@ var resourcesMap map[string]importable = map[string]importable{
 			{Path: "library.jar", Resource: "databricks_dbfs_file", Match: "dbfs_path"},
 			{Path: "library.whl", Resource: "databricks_dbfs_file", Match: "dbfs_path"},
 			{Path: "library.egg", Resource: "databricks_dbfs_file", Match: "dbfs_path"},
+                        {Path: "policy_id", Resource: "databricks_cluster_policy"},
```
Comment (nfx) [inline exporter/importables.go:210]: Thank you! Can you also run "make fmt"?

**Review by nfx — CHANGES_REQUESTED** [review]

File: exporter/importables.go (hunk 1 above)
Comment (david-lyle) [reply exporter/importables.go]: You bet, done!

**Review by nfx — APPROVED** [review]
lgtm
