### PR TITLE
fix applying changes in absence of the email_notifications block

### LINKED ISSUE #530: [ISSUE] Plan shows change for email_notifications block in databricks_job when not set
### Terraform Version
Terraform v0.14.6
+ provider registry.terraform.io/databrickslabs/databricks v0.3.0

### Affected Resource(s)
- databricks_job

### Environment variable names
None

### Expected Behavior
Plan shows no change between applies when email_notification block is not provided

### Actual Behavior
Plan shows a change for email_notifications between applies when email_notifications block is not provided
```
  # module.databricks_jobs["data_export"].databricks_job.job will be updated in-place
  ~ resource "databricks_job" "job" {
        id                        = "XXX"
        name                      = "XXX"
        # (6 unchanged attributes hidden)

      - email_notifications {
          - no_alert_for_skipped_runs = false -> null
          - on_failure                = [] -> null
          - on_start                  = [] -> null
          - on_success                = [] -> null
        }



        # (3 unchanged blocks hidden)
    }
```

### Steps to Reproduce
1. Create a databricks_job resource with no email_notifications block
2. run `terraform apply`
3. run `terraform plan` or `terraform apply` to see the plan with erroneous change

### PR DESCRIPTION
**Pull request by alexott**
it also happened when `max_concurrent_runs` wasn't provided

this fixes #530

### CODE REVIEW

File: compute/resource_job.go [hunk 1]
```diff
@@ -126,6 +126,14 @@ var jobSchema = common.StructToSchema(JobSettings{},
 				return false
 			}
 		}
+		s["email_notifications"].DiffSuppressFunc = func(k, old, new string, d *schema.ResourceData) bool {
+			log.Printf("[INFO] k='%v', old='%v', new='%v'", k, old, new)
+			if old == "1" && new == "0" {
```
Comment (nfx) [inline compute/resource_job.go:131]: `no_alert_for_skipped_runs` is an integer?

Comment (alexott) [reply compute/resource_job.go:131]: No. This field is a list, so it receives length of that list, and diff on individual fields isn’t called (maybe it’s called if the predefined value changes, but it should be handled by default parameters).

**Review by nfx — APPROVED** [review]
