### PR TITLE
Propagate `tf:"suppress_diff"` to child attributes

### LINKED ISSUE #942: `databricks_instance_pool`.`azure_attributes` configuration drift
I am using a large number of instances and to speed up deployments I want to be able to set some sort of flag that makes sure that instance pools are not recreated. Currently, whenever I run `terraform apply`, all existing pools are deleted and new pools are created. I noticed that it takes up to 15 minutes until all clusters are up and running again.

This feature would be particularly useful for me during development: I frequently find myself deploying some feature branch to one of our Databricks workspaces to test out some features, and each time I do that I need to wait 5-10 minutes until all instances are recreated.

Is there an option to disable the deletion/creation of instance pools during `terraform apply`?

### Configuration

A subset of the configuration that I use:

```hcl
terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.3.11"
    }
  }
}

provider "databricks" {}

data "databricks_spark_version" "latest" {
  latest = true
  scala = "2.12"
  spark_version = "3"
}

resource "databricks_instance_pool" "nodes_d3" {
  instance_pool_name = "D3 2.12 latest"
  min_idle_instances = 0
  max_capacity = 20
  node_type_id = "Standard_D3_v2"

  idle_instance_autotermination_minutes = 15

  preloaded_spark_versions = [
    data.databricks_spark_version.latest.id
  ]

  azure_attributes {
    availability = "SPOT_AZURE"
  }
}

resource "databricks_job" "some_job" {
  name = "Some Spark job"

  new_cluster {
    spark_version = data.databricks_spark_version.latest.id
    instance_pool_id = databricks_instance_pool.nodes_d3.id

    # Single-node config
    spark_conf = {
      "spark.databricks.cluster.profile" = "singleNode"
      "spark.master" = "local[*]"
    }

    custom_tags = {
      "ResourceClass" = "SingleNode"
    }
  }

  # will auto-restart the cluster on update
  always_running = true

  # retry indefinitely
  max_retries = local.max_retries
  min_retry_interval_millis = local.min_retry_interval

  library {
    jar = "/some/path/to/a.jar"
  }

  spark_jar_task {
    main_class_name = "Startup"
  }
}
```

### Expected Behavior

There should be an option to disable the delete/create of the instance pools.

### Actual Behavior

Every time I run `terraform apply` the pools get deleted and recreated.

### Steps to Reproduce

1. use the config above
2. apply: the pools get created
3. apply again: the pools get deleted and re-created

### Terraform and provider versions

- Terraform: 1.0.11
- Databricks provider: 0.3.11

### PR DESCRIPTION
**Pull request by nfx**
* Propagate diff suppression also to nested fields of a configuration block, if it's marked for diff suppression.
* Log more precise log messages when this happens.

Fix #942

### CODE REVIEW

**Review by alexott — APPROVED** [review]
Lgtm. Very elegant

File: common/resource.go [hunk 1]
```diff
@@ -137,9 +136,8 @@ func MustCompileKeyRE(name string) *regexp.Regexp {
 func makeEmptyBlockSuppressFunc(name string) func(k, old, new string, d *schema.ResourceData) bool {
 	re := MustCompileKeyRE(name)
 	return func(k, old, new string, d *schema.ResourceData) bool {
-		log.Printf("[DEBUG] name=%s k='%v', old='%v', new='%v'", name, k, old, new)
 		if re.Match([]byte(name)) && old == "1" && new == "0" {
-			log.Printf("[DEBUG] Suppressing diff for name=%s k=%#v old=%#v new=%#v", name, k, old, new)
+			log.Printf("[DEBUG] Suppressing diff for name=%s k=%#v patform=%#v config=%#v", name, k, old, new)
```
Comment (kthejoker) [inline common/resource.go:140]: typo, should. be platform

Comment (nfx) [reply common/resource.go:140]: @kthejoker thanks! will be fixed along in the other prs
