### PR TITLE
Don't restart cluster on changes that doesn't affect it (issue #379)

### LINKED ISSUE #379: [ISSUE] Changing Pinned status causes cluster restart
The change in the pinned status for existing cluster causes the cluster restart because `/clusters/edit` REST API is not idempotent. We need to implement more sophisticated state comparison, and call `/clusters/edit` only if actual cluster definition has changed.  The cluster restart may also happen if we just add library, etc.

### Terraform Version

Terraform v0.13.4, Databricks provider is built from Git today

### Affected Resource(s)
- databricks_cluster

### Terraform Configuration Files

Initial:

```hcl
resource "databricks_cluster" "test_libs" {
  cluster_name            = "Test Maven"
  spark_version           = "7.3.x-scala2.12"
  node_type_id            = "Standard_D3_v2"
  autotermination_minutes = 20

  autoscale {
    min_workers = 1
    max_workers = 2
  }
}
```
modified:

```hcl
resource "databricks_cluster" "test_libs" {
  cluster_name            = "Test Maven"
  spark_version           = "7.3.x-scala2.12"
  node_type_id            = "Standard_D3_v2"
  autotermination_minutes = 20
  is_pinned               = true

  autoscale {
    min_workers = 1
    max_workers = 2
  }
}
```

### Debug Output

Debug output: https://gist.github.com/alexott/77d1e43786d6b9981299b6682d0dcfd3

### Expected Behavior

Cluster shouldn't be restarted, only pinned status change happens

### Actual Behavior

Cluster is restarted, and pinned status changes

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. change the pinned status of the existing cluster
1. execute `terraform apply`

### PR DESCRIPTION
**Pull request by alexott**
This PR adds detection of what cluster parameters were changed, and call `/clusters/edit`
only we changed parameters that are related to cluster directly, not things like
`is_pinned` or `library`...

This fixes #379

### CODE REVIEW

File: compute/resource_cluster.go [hunk 1]
```diff
@@ -277,6 +279,18 @@ func legacyReadLibraryListFromData(d *schema.ResourceData) (cll ClusterLibraryLi
 	return
 }
 
+func hasClusterConfigChanged(d *schema.ResourceData) bool {
+	for k := range clusterSchema {
+		if strings.HasPrefix(k, "library") || k == "is_pinned" {
+			continue
+		}
+		if d.HasChange(k) {
```
Comment (nfx) [inline compute/resource_cluster.go:287]: can you add a unit test to it? :)

**Review by nfx — CHANGES_REQUESTED** [review]
can you add a unit-test?

File: compute/resource_cluster.go [hunk 2]
```diff
@@ -277,6 +279,18 @@ func legacyReadLibraryListFromData(d *schema.ResourceData) (cll ClusterLibraryLi
 	return
 }
 
+func hasClusterConfigChanged(d *schema.ResourceData) bool {
+	for k := range clusterSchema {
+		if strings.HasPrefix(k, "library") || k == "is_pinned" {
```
Comment (nfx) [inline compute/resource_cluster.go:284]: + `libraries` key itself.

Comment (nfx) [reply compute/resource_cluster.go:284]: because `library_` is deprecated and would be removed in few weeks

**Comment by alexott** [comment]
it's interesting question - about unit testing of "incremental" change.  I've looked through existing testing infrastructure, and couldn't figure out how to do a "single" change to the existing state - right now you need to provide complete state (with Spark version, etc.), but it will trigger the `/clusters/edit` as before...

**Review by nfx — APPROVED** [review]
I'll change it to 0.2.8 :)
